### ISSUE TITLE
python main.py config/diamond_task_C.yaml

### ISSUE THREAD

**Issue by naushy** [filyp/cognitive_tasks#1]
python main.py config/diamond_task_C.yaml
Traceback (most recent call last):
  File "main.py", line 95, in <module>
    run()
  File "main.py", line 60, in run
    participant_info, experiment_version = get_participant_info(config.get("Ask_for_experiment_version", False))
  File "C:\Users\user\cognitive_tasks\classes\experiment_info.py", line 11, in get_participant_info
    my_dlg = gui.Dlg(title="Participant info")
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\psychopy\gui\qtgui.py", line 180, in __init__
    buttons = QtWidgets.QDialogButtonBox.StandardButton.Ok | QtWidgets.QDialogButtonBox.StandardButton.Cancel
AttributeError: type object 'QDialogButtonBox' has no attribute 'StandardButton'

**Comment by filyp** [comment]
Looks like some wrong psychopy or qt version.
